### PR TITLE
opayo lib configure docs update

### PR DESCRIPTION
**Pull request by uzaif313**
@peterberkenbosch I did added documentation for configure opayo lib. let me know if you want any update from my side 🤞🏽

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
Thanks @uzaif313. Go get that t-shirt! ;)

**Comment by uzaif313** [comment]
@peterberkenbosch Sorry I didnt get you.

**Comment by peterberkenbosch** [comment]
No worries, I referred to hacktoberfest. Anyway thanks for your contribution.

**Comment by uzaif313** [comment]
@peterberkenbosch I am using sagepay(opayo) in my project and i created one class through which i am doing all transaction and refund. I want to contribute in your project. right now i am going through the code. thanks for opayo gem.

**Comment by peterberkenbosch** [comment]
Great @uzaif313 Thanks! I'll be merging in some transaction code too. #2 for example is almost ready to go

**Comment by uzaif313** [comment]
@peterberkenbosch looks good 👍🏽.

**Pull request merged**
